/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.pm2.demo.gradle.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
